### ISSUE TITLE
Feature: Add x32 Control Module

### ISSUE THREAD

**Issue by jeffmikels** [jeffmikels/propresenter-watcher#1]
Probably should use node-osc instead of osc.js because no compiling is needed.

However, node-osc is probably slower.

**Comment by jeffmikels** [comment]
We could use the library here:
https://sites.google.com/site/patrickmaillot/x32

An example would be bpm[120] to automatically set the tap tempo setting on the x32

**Comment by jeffmikels** [comment]
github repo: https://github.com/pmaillot/X32-Behringer

**Comment by cgarwood** [comment]
StreamDeck companion has a partial x32 module as well: https://github.com/bitfocus/companion-module-x32/blob/master/index.js
