### ISSUE TITLE
Clearing lower thirds

### ISSUE THREAD

**Issue by cgarwood** [jeffmikels/propresenter-watcher#7]
On modularize branch:

When hitting a slide with no text and a vmix trigger to remove an overlay we see the text go away and just see a blank lower third (only background) for about 1 second before vmix gets the overlay out trigger and fades it out

**Comment by jeffmikels** [comment]
Weird... I wonder what's causing the delay... Maybe I can make all the "triggers" operate asynchronously.

**Comment by jeffmikels** [comment]
I changed the order of the events... now, the configured triggers will all get notified before the lower3 ui is updated.
